---

- name: UPDATE & UPGRADE PACKAGES
  hosts: all
  become: true

  tasks:

  - name: Update the package list
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: dist
